### ISSUE TITLE
Dress Rehearsal Review

### ISSUE THREAD

**Issue by MatthewBorabo** [GavinCopley/sharedGame#10]
**Hook:** (Everyone/Template)
Points: 3.9/4.0
Explanation: HOOK / First Impressions: The pre-game (CODECLIMBERS name) is very appealing and provides some suspense before starting the game. It is a nice introduction. After the main menu, You are greeted with the first level, which has a nice background and some platforms to jump on. 3.8/4.0

**Knowledge**:
Points: 3.85/4.0
Explanation: We incorporated the OOP (Object-Oriented Programming) for the player and the platform with success.

**Value**:
Points: 0.9/1.0
Explanation: The main aspect of the game is the platforming. The player is able to jump without the glitch of double jumping and goes at a reasonable speed. There is no sprite for the game however. Despite that, I think the value still deserves a 90% since you are also able to switch between levels which have more platforms! 

_Miscellaneous:_

**_WOW_** Factor:

1. Some arrows show where the player is facing, so if you press "d" it'll show the arrow on the right, and if you press "a," it'll show the arrow on the left.

2. You can jump only once, but you can jump high up in the air when pressing w. You can also jump mid-air when falling, but not when jumping up and falling.

3. The camera moves along with the player and mocks the direction it goes to, so if the character goes left, it'll go left as well, and if the character goes to the right, it'll go to the right. However, if the character jumps up, it'll not mock that movement since there's nothing above to show.

**Presentation:** The way the game is presented is nice, as it greets you with the main title screen which has a really nice fade in and fade out effect before redirecting you to the game. (fyi the index.html is the title screen and the home.html is the game). Furthermore, the game itself has a nice city theme, which was made solely by Gavin Copley.

**What didn't make it:** 
There are many parts that weren't out to make it into the game, whether it was time management, hard to implement and etc. One part that wasn't able to get it was Ian's questions about code. This was going to be the main aspect of the game (making the name CodeClimbers). However, we didn't have enough time to implement the questions or where we could implement them in the platforming game. Ian was able to provide SEVEN questions about code, which are multiple choice. 
Another part that wasn't able to make it was the sprites. We weren't able to provide the sprites for the game, as there was trouble incorporating the animation with smoothness. To be honest though, I just like the square box (like Geometry Dash).

Extra: +0.5 Points

**TOTAL:** 9.15 / 10 (91.5%)

**Comment by MatthewBorabo** [comment]
HOOK / First Impressions: The pre-game (CODECLIMBERS name) is very appealing and provides some suspense before starting the game. It is a nice introduction. After the main menu, You are greeted with the first level, which has a nice background and some platforms to jump on. :) 3.8/4.0

**Comment by Im2008** [comment]
WOW FACTOR: 
1) Some arrows show where the player is facing, so if you press "d" it'll show the arrow on the right, and if you press "a," it'll show the arrow on the left.

2) You can jump only once, but you can jump high up in the air when pressing w. You can also jump mid-air when falling, but not when jumping up and falling.

3) The camera moves along with the player and mocks the direction it goes to, so if the character goes left, it'll go left as well, and if the character goes to the right, it'll go to the right. However, if the character jumps up, it'll not mock that movement since there's nothing above to show.

**Comment by NateTurman** [comment]
Hook: 3.9/4.0
The loading screen was very cool and interesting as it loaded in and out giving a good idea of what the game was going to be. The sprites looked very clear and understandable for being homemade.
Knowledge: 3.8/4.0
They demonstrated a very well understanding of code and using it to make their game.
Value: 1/1
The game is very well made with the jumps being realistic and the platforms being spaced apart enough for it to be a hard jump but still do-able.
WOW Factor 1/1
The sprite of the red box had an arrow on it that pointed in the direction the player was going towards. Also, the arrow had an animation for the way it was facing.
Finally, all the sprites were homemade and looked very professional for a beginner high school class.

97/100

**Comment by AZaletski24** [comment]
Hook: 3.81/4 
The game name and color palette are both very appealing, leading to a good first impression as a result of good structural organization.

Knowledge: 3.93/4
The OOP and use of concepts discussed in class is clearly present and well-executed within the game.

Value: 0.92/1
The game is very engaging and can be played for an extended period of time, great value here.

WOW Factor: 0.85/1
The game was really fun and had a lot of cool and unique aspects. Nice job!

**Comment by VanceReynolds** [comment]
Hook: 3.9/4
The game's title and color scheme are fun and attractive popping out to me at first look and creating a strong initial impression.

Knowledge: 3.8/4
The game effectively incorporates object-oriented programming principles and well applies class concepts learned in the course.

Value: 0.95/1
The game is engaging and has lots of replayability one of my favorite things from the entire night.

WOW Factor: 0.9/1
Had a lot of fun seeing this project. Great work!
